django/app/shows/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from app.shows.views import *
app_name = 'shows'

urlpatterns = [
    # get list of most popular tv shows
    path('', views.index, name='index'),

    # filter list of tv shows by name
    path('show/<str:name>/', views.show_search, name='show_search'),

    # filter list of tv shows by releases date
    path('releases/<int:year>/', views.first_air_date_year, name='first_air_date_year'),

    # sort tv shows by popularity
    path('popularity/<str:popularity>/', views.popularity, name='popularity'),

    # allows to vote for the choosen tv show
    path('rating/', views.rating, name='rating'),
]

django/themoviedb/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.shows.urls')),
]

django/app/shows/models.py
from django.db import models

# Create your models here.

django/app/shows/views.py
from django.conf import settings
from django.http import Http404, HttpResponse ,HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
import  json, requests

# authentication function make multples calls to the external API
# require api_key generated at te admin panel of the provider API
#  this api_key and the base url can be change at the settin.py of the project

def authentication():
    #  get the first request_token with the api_key
    api_url = f'{ settings.BASE_URL }/authentication/token/new?api_key={ settings.API_KEY }'
    response = requests.get(api_url)
    authentication = response.json()
    request_token = authentication["request_token"]

    # get the second request_token with the api_key and the first token
    # also the credentials of the user are need it
    # to get the session_id
    api_url = f'{ settings.BASE_URL }/authentication/token/validate_with_login?api_key={ settings.API_KEY }'
    payload = {
        'request_token': request_token,
        'username': settings.API_USERNAME,
        'password': settings.API_PASSWORD,
    }
    response = requests.post(api_url, data=payload)
    authentication = response.json()
    request_token = authentication["request_token"]

    # finally get the session_id which allow to rate the shows later in the code
    api_url = f'{ settings.BASE_URL }/authentication/session/new?api_key={ settings.API_KEY }'
    payload = {'request_token': request_token}
    response = requests.post(api_url, data=payload)
    session_id = response.json()
    return session_id['session_id']

# get list of most popular tv shows
def index(request,page="1"):
    page = str(request.GET.get('page'))
    api_url = f'{ settings.BASE_URL }/tv/popular?api_key={ settings.API_KEY }&page={ page }'
    response = requests.get(api_url)
    shows = response.json()
    return render(request, 'index.html', {'shows': shows })

# filter list of tv shows by name
def show_search(request,name="",page="1"):
    page = str(request.GET.get('page'))
    api_url = f'{ settings.BASE_URL }/search/tv?api_key={ settings.API_KEY }&page={ page }'
    api_url += f'&include_adult=false&query={ name }'
    response = requests.get(api_url)
    shows = response.json()
    return render(request, 'index.html', {'shows': shows })

# filter list of tv shows by releases date
def first_air_date_year(request,year="",page="1"):
    page = str(request.GET.get('page'))
    api_url = f'{ settings.BASE_URL }/discover/tv?api_key={ settings.API_KEY }&page={ page }'
    api_url += f'&include_null_first_air_dates=false&first_air_date_year={ str(year) }'
    response = requests.get(api_url)
    shows = response.json()
    return render(request, 'index.html', {'shows': shows })

# sort tv shows by popularity
def popularity(request,popularity="",page='1'):
    page = str(request.GET.get('page'))
    api_url = f'{ settings.BASE_URL }/discover/tv?api_key={ settings.API_KEY }&page={ page }'
    api_url += f'&include_null_first_air_dates=false&sort_by={ popularity }'
    response = requests.get(api_url)
    shows = response.json()
    return render(request, 'index.html', {'shows': shows })

# allows to vote for the choosen tv show
def rating(request):
    data = json.loads(request.body.decode("utf-8"))
    value = str(data['value'])
    tv_id = str(data['tv_id'])
    session_id = authentication()
    api_url = f'{ settings.BASE_URL }/tv/{ tv_id }/rating?api_key={ settings.API_KEY }&session_id={ session_id }'
    payload = {'value': value}
    response = requests.post(api_url, data=payload)
    response = response.json()
    # print(response)
    return JsonResponse(response)

django/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport"
					content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link rel="shortcut icon" href="" />
    <title>{% block title %}The Movie Database{% endblock %}</title>
  </head>
  <body>
		{% include  'navbar.html' %}
		<br>
		{% block content %}
		<h4>	base </h4>
		{% endblock %}
  </body>
  <footer>
    <script src="{% static 'js/scripts.js' %}"></script>
  </footer>
</html>

django/templates/index.html
{% extends 'base.html' %}
{% load static %}
<div class="row">
  <div class="col-sm">
    {% block content %}
    <div class="container-fluid">
      <div id="csrf_token"> {% csrf_token %} </div>
      <!-- NAVIGATION -->
      <div class="row">
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            <li class="page-item"><a class="page-link" onclick="changePage('{{ shows.page  }}'- 1)">Previous</a></li>
            <li class="page-item"><a class="page-link" onclick="changePage('1')">First</a></li>
            <li class="page-item"><a class="page-link" onclick="changePage('{{ shows.total_pages }}')">Last</a></li>
            <li class="page-item"><a class="page-link" onclick="changePage(Number('{{ shows.page }}') + 1)">Next</a></li>
          </ul>
        </nav>
      </div>
      <!-- MAIN BLOCK -->
      <!-- BOOTSTRAP TABLE -->
      <div class="row">
        <div class="col-sm-4" style="align-content: center;">
          <label for="name">Nome</label>
           <input type="text" value="" id="name" onchange="changeHandler('name')" autocomplete="on">
        </div>
        <div class="col-sm-4" style="align-content: center;">
          <label for="first_air_date">ano de lançamento</label>
           <input type="text" value="" id="first_air_date" onchange="changeHandler('first_air_date')" autocomplete="on">
        </div>
        <div class="col-sm-4" style="align-content: center;">
          <label for="popularity">popularidade</label>
          <select name="popularityFilter" id="popularity" onchange="changeHandler('popularity')">
            <option value="" selected></option>
            <option value="popularity.asc"> ASC</option>
            <option value="popularity.desc"> DESC</option>
          </select>
        </div>
      </div>
      <div class="row">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">nome</th>
              <th scope="col">descrição</th>
              <th scope="col">pôster</th>
              <th scope="col">popularidade</th>
              <th scope="col">primeiro episódio</th>
              <th scope="col">gêneros</th>
              <th scope="col">avaliações </th>
              <th scope="col">avaliar</th>
            </tr>
          </thead>
          <tbody>
            {% for item in shows.results %}
              <!-- <p>{{ shows.results }}</p> -->
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.name }}</td>
                <td>{{ item.overview }}</td>
                <td><img src="https://image.tmdb.org/t/p/w500/{{ item.poster_path }}" alt="N/T" style="width: 70%;"></td>
                <td>{{ item.popularity }}</td>
                <td>{{ item.first_air_date }}</td>
                <td>{{ item.genre_ids }}</td>
                <td>{{ item.vote_count }}</td>
                <td>
                  <div class="input-group" style="width: 120px;">
                    <input type="number" class="form-control" name="rating" id="rating{{ item.id }}" min="0.5" max="10">
                    <button type="button" class="btn btn-success btn-sm" onclick="rating('rating{{ item.id }}','{{ item.id }}')"> Rate </button>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

    </div>
    {% endblock %}
  </div>
</div>

django/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #83d0f2;">
  <div class="linksign">
    <a class="navbar-brand" href="{% url 'shows:index' %}" style="margin-left: 15%;">
      <!-- Home -->
      <!-- <img src="{% static 'img/notes_logo.png' %}" width="30" height="30" alt=""> -->
      <img src="{% static 'img/list-alt.svg' %}" alt="logo" width="30" height="30" >
    </a>
  </div>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">

      {% if user.is_staff %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'shows:index' %}">Categories</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link linksign" href="{% url 'shows:index' %}">Tags</a>
        </li>
      {% else %}
        <li class="nav-item active">
        </li>
      {% endif %}


    </ul>
    <span class="navbar-text" style="color:black;">
      {% block welcome_message %}
        {% if user.is_authenticated %}
          <h5>Welcome to Notes {{ user.username }}!!!</h5>
        {% else %}
          The Movie Database
        {% endif %}
      {% endblock %}
    </span>
  </div>
</nav>